name: Circlek Monitor Checks

on:
  pull_request:
    branches: [master]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check Python syntax
        run: python -m py_compile monitor.py fuel.py

      - name: Install Pytest
        run: pip install pytest
      
      - name: Pytest
        run: pytest

      - name: failure alert
        if: ${{ failure() }}
        run: echo "Alert Pipeline failure detected"

      - name: Condition run
        if: ${{ success() }}
        run: echo "Condition was successful"